# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'LeetLoot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeetLoot
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  
  # Pods for Twitter
  pod 'TwitterKit'
  
  pod 'WARangeSlider'

  target 'LeetLootTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
