# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'LeetLoot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  
  # Pods for Firebase Storage
  pod 'Firebase/Storage'
  
  # Pods for Twitter
  pod 'TwitterKit'

  # Pods for Slider
  pod 'RangeSeekSlider', :git => 'https://github.com/WorldDownTown/RangeSeekSlider.git', :branch => 'swift_4'

  target 'LeetLootTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
