# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeetLoot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeetLoot
  pod 'Firebase/Core'

  target 'LeetLootTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
